services:
  db-test:
    image: postgres:15
    container_name: video-processor-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video_processor_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
